/* Customization for Nuxt-purgecss */
{
	/*
	 What shall nuxt-purgecss scan in order to remove unused css from build bundle?
	 When NOT using static site generation with nuxt then project must be carefully analyzed by purge
	 A person with project insight must analyze the project and keep the following customization updated. 
	 It is time consuming process with risk that something is missed and removed from bundle anyway. 
	*/
	/* RECCOMENDED CONFIGURATION METHOD: static-generated-html
		Use Nuxt SSG (Static Site Generation) first to pre build all html with generated classes.  
		Then build again for production with that generated html as content templates for purge. 
		In that way purge always find all classes & selectors generated in the final html! 
	*/
}

// Default safelist - https://github.com/Developmint/nuxt-purgecss/blob/main/src/config.ts
const defaultSafelist = [
	// 'body',
	// 'html',
	// 'nuxt-progress',
	// '__nuxt',
	// /-(leave|enter|appear)(|-(to|from|active))$/, // Normal transitions
	// /^nuxt-link(|-exact)-active$/, // Nuxt link classes
	// /^(?!cursor-move).+-move$/, // Move transitions
	// /.*data-v-.*/, // Keep scoped styles
	// // New Vue3 selectors
	// /:slotted/,
	// /:deep/,
	// /:global/,
];

// Default content - https://github.com/Developmint/nuxt-purgecss/blob/main/src/config.ts
const defaultContent = [
	// 'components/**/*.{vue,jsx?,tsx?}',
	// 'layouts/**/*.{vue,jsx?,tsx?}',
	// 'pages/**/*.{vue,jsx?,tsx?}',
	// 'composables/**/*.{vue,jsx?,tsx?}',
	// 'App.{vue,jsx?,tsx?}',
	// 'app.{vue,jsx?,tsx?}',
	// 'plugins/**/*.{js,ts}',
	// 'nuxt.config.{js,ts}',
];

/* Vuetify: Additional locations to scan */
const additionalLocations = ['modules/purgecss/static-generated-html/**/*.html'];

/* Vuetify: Selectors (runtime generated) better never not to remove */
const vuetifySafelist = [
	// /v-application/, // generated by vApp
	// /v-layout/, // generated by vApp
	// /v-toolbar/, // generated by vAppBar
	// /v-locale/,  // generated runtime by i.e vBtn if locale enabled
	// /v-icon/,  // generated by vBtn
	// /flex-grow-1/, // generated by v-spacer
	// /v-responsive/, // generated eager
];

/* Vuetify: Components and directives used in this project */
const usedComponents = [
	/v-ripple/, // when enabled, generated at runtime by vBtn
	// /v-app/,
	// /v-app-bar/,
	// /v-app-bar-nav-icon/,
	// /v-navigation-drawer/,
	// /v-toolbar-title/,
	// /v-container/,
	// /v-sheet/,
	// /v-main/,
	// /v-card/,
	// /v-btn/,
	// /v-col/,
	// /v-row/,
];

export default {
	content: [...defaultContent, ...additionalLocations],
	safelist: {
		greedy: [...vuetifySafelist, ...usedComponents],
		standard: [...defaultSafelist],
	},
};
